# Copyright 2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.2

EAPI=8

CRATES="
	addr2line-0.19.0
	adler-1.0.2
	atty-0.2.14
	autocfg-1.1.0
	backtrace-0.3.67
	bitflags-1.3.2
	cc-1.0.78
	cfg-if-1.0.0
	colored-1.9.3
	crossbeam-channel-0.5.6
	crossbeam-deque-0.8.2
	crossbeam-epoch-0.9.13
	crossbeam-utils-0.8.14
	darling-0.9.0
	darling_core-0.9.0
	darling_macro-0.9.0
	derive_builder-0.7.2
	derive_builder_core-0.5.0
	either-1.8.0
	failure-0.1.8
	failure_derive-0.1.8
	fastrand-1.8.0
	fixedbitset-0.1.9
	fnv-1.0.7
	fs_extra-1.2.0
	getopts-0.2.21
	gimli-0.27.0
	hashbrown-0.12.3
	hermit-abi-0.1.19
	hermit-abi-0.2.6
	ident_case-1.0.1
	indexmap-1.9.2
	instant-0.1.12
	itertools-0.8.2
	jemalloc-sys-0.1.8
	jemallocator-0.1.9
	lazy_static-1.4.0
	libc-0.2.139
	maybe-uninit-2.0.0
	memchr-2.5.0
	memoffset-0.7.1
	miniz_oxide-0.6.2
	num-traits-0.2.15
	num_cpus-1.15.0
	object-0.30.0
	pathfinding-1.1.12
	proc-macro2-0.4.30
	proc-macro2-1.0.49
	quote-0.6.13
	quote-1.0.23
	rayon-1.6.1
	rayon-core-1.10.1
	redox_syscall-0.2.16
	remove_dir_all-0.5.3
	rustc-demangle-0.1.21
	scopeguard-1.1.0
	seahash-3.0.7
	smallvec-0.6.14
	strsim-0.7.0
	strsim-0.8.0
	syn-0.15.44
	syn-1.0.107
	synstructure-0.12.6
	tempfile-3.3.0
	unicode-ident-1.0.6
	unicode-width-0.1.10
	unicode-xid-0.1.0
	unicode-xid-0.2.4
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="This is very specialized reimplementation of quilt & patch in one. It supports only the push command. The goal is to be very fast."
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/openSUSE/rapidquilt"
SRC_URI="https://github.com/openSUSE/${PN}/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris)"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"
